<?php

/**
 * @file
 * .
 */

/**
 * Implements hook_xmlrpc().
 */
function monitor_status_agent_xmlrpc() {
  return [
    [
      'monitor.status',
      'monitor_status_agent_callback',
      [
        'base64',
        'base64',
      ],
      t('Get site status'),
    ],
  ];
}

/**
 * .
 */
function monitor_status_agent_callback($crypt_key) {
  if (empty($crypt_key)) {
    return xmlrpc_error(400, t('Invalid request.'));
  }

  $config = \Drupal::config('monitor_status_agent.settings');
  $priv_key = $config->get('monitor_status_agent_private_key');

  if (openssl_private_decrypt($crypt_key, $key, $priv_key)) {
    $available = update_get_available(TRUE);
    $data = $available;

    $cipher = 'AES-256-CBC';
    $ivlen = openssl_cipher_iv_length($cipher);
    $iv = openssl_random_pseudo_bytes($ivlen);
    $cipher_data = openssl_encrypt(serialize($data), $cipher, $key, OPENSSL_RAW_DATA, $iv);
    $hmac = hash_hmac('sha256', $cipher_data, $key, true);
    $pub_key = $config->get('monitor_status_agent_dashboard_key');

    if (openssl_public_encrypt($iv, $crypt_iv, $pub_key)) {
      return base64_encode(serialize([$crypt_iv, $hmac, $cipher_data]));
    }
  }

  return xmlrpc_error(400, t('Invalid request.'));
}

